### ISSUE TITLE
libbpf: sec 'tracepoint/syscalls/sys_enter_kill': failed to find program symbol at offset 0

### ISSUE THREAD

**Issue by robyn-he** [niclashedam/ebpf-kill-example#8]
there is a problem with me,how should I solve it？

libbpf: sec 'tracepoint/syscalls/sys_enter_kill': failed to find program symbol at offset 0
The kernel didn't load the BPF program

**Comment by niclashedam** [comment]
Hi @boyanghe.
What OS do you run and which kernel version?

**Comment by jibanes** [comment]
same here
debian 10
amd64
4.19.128

**Comment by niclashedam** [comment]
@qmonnet Do you have some insights into why libbpf aren't able to find the program symbol? I'm able to reproduce this on Debian 10 with kernel 4.19 on AWS.

**Comment by qmonnet** [comment]
I think I've seen that before but I don't remember. My guess is that it could be some bug in an older version of libbpf, that might have been fixed since then. Are you able to reproduce on the same env but using a recent libbpf?

**Comment by niclashedam** [comment]
Thanks for the input, @qmonnet. _ebpf-kill-example_ is already using the newest release (0.3), but this issue persist even with the libbpf master branch. Updating to kernel 5.9 does not resolve the issue either.

**Comment by qmonnet** [comment]
Hm. Could it be the clang version, in that case?
(Unlikely to be kernel-related, because this seems to happen when libbpf tries to parse the object file, before it attempts to load it into the kernel.)

**Comment by niclashedam** [comment]
Good catch @qmonnet ! 🎉 
The Debian instance I have here is shipped with clang7, while my Ubuntu instane is shipped with clang10.
Upgrading to clang11 on Debian resolves the issue.

```
admin@ip-172-31-34-121:~/ebpf-kill-example$ clang-11 --version
Debian clang version 11.1.0-++20210204120158+1fdec59bffc1-1~exp1~20210203230823.159
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
admin@ip-172-31-34-121:~/ebpf-kill-example$ make test
./test/test.sh
-- Loading eBPF program.
-- Starting test process to kill.
-- PID of test process is 12615.
-- Killed. Waiting for eBPF program to terminate ..
[ OK ] -- eBPF program ran as expected.
```

Can you try this @jibanes, @boyanghe ?

**Comment by jibanes** [comment]
I've changed clang to clang-11 in src/Makefile
now I get:
```clang-11 -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I/XXX/ebpf-kill-example/src/../libbpf/src//root/usr/include/ \
    -Wall \
    -Werror \
    -O2 -emit-llvm -c -g kern.c
llc -march=bpf -filetype=obj -o kern.o kern.ll
llc: error: llc: kern.ll:14:94: error: expected ')' at end of argument list
define dso_local i32 @ebpf_kill_example(%struct.syscalls_enter_kill_args* nocapture readonly %0) #0 section "tracepoint/syscalls/sys_enter_kill" !dbg !46 {
                                                                                             ^
make[1]: *** [Makefile:24: kern.o] Error 1
make[1]: *** Waiting for unfinished jobs....

```

**Comment by jibanes** [comment]
Same issue with clang-10

**Comment by qmonnet** [comment]
Did you also update `llc` to `llc-11` in the Makefile?

**Comment by jibanes** [comment]
Thanks! that was the clincher.

**Comment by niclashedam** [comment]
Good. I'll add some info about this in the README soon, so we are aware that llvm7 is unsupported.
Thanks for your help @qmonnet !
